package main

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"time"
	"webrtc-playground/internal/operator/coordinator"
	"webrtc-playground/internal/operator/peer"
	"webrtc-playground/internal/worker"
)

const (
	nodeTypePeer  = "PEER"
	nodeTypeCoord = "COORD"
	peerTimeout   = 5 * time.Second
)

type WorkerFlags struct {
	Mode        string
	NOfMessages int
	Username    string
	Directory   string
	Recursive   bool
}

func setupWorkerFlags(workerFlags *WorkerFlags) {
	// TODO: setup worker flags
	modeFlagDescription := fmt.Sprintf("Worker worker, can either be %v, %v or %v", worker.WorkerRandMessages, worker.WorkerChat, worker.WorkerFS)
	flag.StringVar(&workerFlags.Mode, "worker", worker.WorkerRandMessages, modeFlagDescription)

	nOfMessagesFlagDescription := fmt.Sprintf("worker: %v, number of random messages need to be generated by workers", worker.WorkerRandMessages)
	flag.IntVar(&workerFlags.NOfMessages, "n_of_messages", worker.DEFAULT_N_OF_MESSAGES, nOfMessagesFlagDescription)

	usernameFlagDescription := fmt.Sprintf("worker: %v, arbitrary username for chat user", worker.WorkerChat)
	flag.StringVar(&workerFlags.Username, "username", worker.DefaultUsername, usernameFlagDescription)

	directoryFlagDescription := fmt.Sprintf("worker : %v, directory which should be updated/monitored for updates by this worker", worker.WorkerFS)
	flag.StringVar(&workerFlags.Directory, "directory", worker.DefaultPath, directoryFlagDescription)
	recursiveFlagDescription := fmt.Sprintf("worker : %v, whether subdirectories should be monitored as well", worker.WorkerFS)
	flag.BoolVar(&workerFlags.Recursive, "recursive", worker.DefaultRecursive, recursiveFlagDescription)

}

func createWorkerFromFlags(workerFlags *WorkerFlags) (w worker.Worker, err error) {
	err = errors.New("unknown mode of worker")

	switch workerFlags.Mode {
	case worker.WorkerRandMessages:
		w, err = worker.NewRandMessageWorker(workerFlags.NOfMessages)
	case worker.WorkerChat:
		w, err = worker.NewChatWorker(workerFlags.Username)
	case worker.WorkerFS:
		w, err = worker.NewFSWorker(workerFlags.Directory, workerFlags.Recursive)
	}

	return
}

func main() {
	var nodeType, coordAddress string
	workerFlags := WorkerFlags{}

	coordPort := flag.Int("coordinator_port", -1, "Port on which coordinator runs, mandatory field")
	flag.StringVar(&nodeType, "node_type", "", "Determines which logic should node enforce, mandatory field")
	flag.StringVar(&coordAddress, "coordinator_address", "", "Address for coordinator node, mandatory field")

	setupWorkerFlags(&workerFlags)

	flag.Parse()
	if nodeType == "" || *coordPort == -1 {
		fmt.Fprintf(os.Stderr, "Mandatory fields were missing, please check -h\n")
		os.Exit(1)
	}

	w, err := createWorkerFromFlags(&workerFlags)
	// Only peer node needs worker
	if nodeType == nodeTypePeer && err != nil {
		fmt.Fprint(os.Stderr, err)
		os.Exit(1)
	}

	switch nodeType {
	case nodeTypePeer:
		// Await for some arbitrary duration to let coordinator node start up
		fmt.Printf("Peer has been started, waiting for %v\n", peerTimeout)
		time.Sleep(peerTimeout)

		peerNode, err := peer.New(coordAddress, *coordPort, &w)
		if err != nil {
			fmt.Fprint(os.Stderr, err)
			os.Exit(1)
		}

		if err := peerNode.InitConnection(); err != nil {
			fmt.Fprint(os.Stderr, err)
			os.Exit(1)
		}

		if err := peerNode.Await(); err != nil {
			fmt.Fprint(os.Stderr, err)
			os.Exit(1)
		}

		fmt.Printf("Peer Node completed successfully\n")
	case nodeTypeCoord:
		coordNode, err := coordinator.New(*coordPort)
		if err != nil {
			panic(err)
		}
		coordNode.Listen()
	default:
		fmt.Fprintf(os.Stderr, "Node type is not correct, it can be following: [%v, %v]", nodeTypeCoord, nodeTypePeer)
		os.Exit(1)
	}
}
